documents:
    path:     /
    controller: App\Controller\Export\Template::index

documents_show:
    path:     /{id}/inscription-{idinscription}/{mode}
    controller: App\Controller\Export\Template::show
    requirements: {mode: preview|show}

documents_new:
    path:     /new
    controller: App\Controller\Export\Template::new

documents_create:
    path:     /create
    controller: App\Controller\Export\Template::create
    requirements: { methods: post }

documents_edit:
    path:     /{id}/edit
    controller: App\Controller\Export\Template::edit

documents_update:
    path:     /{id}/update
    controller: App\Controller\Export\Template::update
    requirements: { methods: post|put }

documents_delete:
    path:     /{id}/delete
    controller: App\Controller\Export\Template::delete

documents_liens:
    path:     /liens
    controller: App\Controller\Export\Template::liens
    requirements: { methods: post }

documents_liensconventions:
    path:     /liens-conventions
    controller: App\Controller\Export\Template::liensConvention
    requirements: { methods: post }

template_copy:
    path:     /copy
    controller: App\Controller\Export\Template::copie
    requirements: { methods: post }

documents_exportfrompreview:
    path:     /exportpreview
    controller: App\Controller\Export\Template::exportfrompreview
    requirements: {methods: post}

document_maj_ordre:
    path: /maj-order
    controller: App\Controller\Export\Template::majOrdre
    requirements: { methods: post }
