documents:
    path:     /
    defaults: { _controller: "OCIMExportBundle:Template:index" }

documents_show:
    path:     /{id}/inscription-{idinscription}/{mode}
    defaults: { _controller: "OCIMExportBundle:Template:show" }
    requirements: {mode: preview|show}

documents_new:
    path:     /new
    defaults: { _controller: "OCIMExportBundle:Template:new" }

documents_create:
    path:     /create
    defaults: { _controller: "OCIMExportBundle:Template:create" }
    requirements: { methods: post }

documents_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCIMExportBundle:Template:edit" }

documents_update:
    path:     /{id}/update
    defaults: { _controller: "OCIMExportBundle:Template:update" }
    requirements: { methods: post|put }

documents_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCIMExportBundle:Template:delete" }

documents_liens:
    path:     /liens
    defaults: { _controller: "OCIMExportBundle:Template:liens" }
    requirements: { methods: post }

documents_liensconventions:
    path:     /liens-conventions
    defaults: { _controller: "OCIMExportBundle:Template:liensConvention" }
    requirements: { methods: post }

template_copy:
    path:     /copy
    defaults: { _controller: "OCIMExportBundle:Template:copie" }
    requirements: { methods: post }

documents_exportfrompreview:
    path:     /exportpreview
    defaults: { _controller: "OCIMExportBundle:Template:exportfrompreview" }
    requirements: {methods: post}
document_maj_ordre:
    path: /maj-order
    defaults: { _controller: "OCIMExportBundle:Template:majOrdre"}
    requirements: { methods: post }
