documents:
    path:     /
    controller: App\Controller\Export\TemplateController::index

documents_show:
    path:     /{id}/inscription-{idinscription}/{mode}
    controller: App\Controller\Export\TemplateController::show
    requirements: {mode: preview|show}

documents_new:
    path:     /new
    controller: App\Controller\Export\TemplateController::new

documents_create:
    path:     /create
    controller: App\Controller\Export\TemplateController::create
    requirements: { methods: post }

documents_edit:
    path:     /{id}/edit
    controller: App\Controller\Export\TemplateController::edit

documents_update:
    path:     /{id}/update
    controller: App\Controller\Export\TemplateController::update
    requirements: { methods: post|put }

documents_delete:
    path:     /{id}/delete
    controller: App\Controller\Export\TemplateController::delete

documents_liens:
    path:     /liens
    controller: App\Controller\Export\TemplateController::liens
    requirements: { methods: post }

documents_liensconventions:
    path:     /liens-conventions
    controller: App\Controller\Export\TemplateController::liensConvention
    requirements: { methods: post }

template_copy:
    path:     /copy
    controller: App\Controller\Export\TemplateController::copie
    requirements: { methods: post }

documents_exportfrompreview:
    path:     /exportpreview
    controller: App\Controller\Export\TemplateController::exportfrompreview
    requirements: {methods: post}

document_maj_ordre:
    path: /maj-order
    controller: App\Controller\Export\TemplateController::majOrdre
    requirements: { methods: post }
