ocim_contacts_intervenants:
    resource: "routing/intervenant.yaml"
    prefix:   /intervenants

ocim_contacts_signataire:
    resource: "routing/signataire.yaml"
    prefix:   /signataire

ocim_contacts_homepage:
    path:     /hello/{name}
    controller: App\Controller\Contacts\Default::index

structure_ajout:
    path:     structure_ajout
    controller: App\Controller\Contacts\Adresse::ajoutTypeStructure

structure:
    path:     structures
    controller: App\Controller\Contacts\Adresse::index
