champPerso:
    path:     /
    controller: App\Controller\Evenements\ChampPersoController::index

champPerso_show:
    path:     /{id}/show
    controller: App\Controller\Evenements\ChampPersoController::show

champPerso_new:
    path:     /new
    controller: App\Controller\Evenements\ChampPersoController::new

champPerso_create:
    path:     /create
    controller: App\Controller\Evenements\ChampPersoController::create
    requirements: { methods: post }

champPerso_edit:
    path:     /evenement-{idevenement}/{generation}
    controller: App\Controller\Evenements\ChampPersoController::edit
    defaults:
        generation : edit
    requirements: 
        generation: generate|edit

champPerso_update:
    path:     /{id}/update
    controller: App\Controller\Evenements\ChampPersoController::update
    requirements: { methods: post|put }

champPerso_delete:
    path:     /{id}/delete
    controller: App\Controller\Evenements\ChampPersoController::delete
    requirements: { methods: post|delete }

champPerso_reponse:
    path:     /update/reponse
    controller: App\Controller\Evenements\ChampPersoController::reponse
    requirements: { methods: post }
