champPerso:
    path:     /
    controller: App\Controller\Evenements\ChampPerso::index

champPerso_show:
    path:     /{id}/show
    controller: App\Controller\Evenements\ChampPerso::show

champPerso_new:
    path:     /new
    controller: App\Controller\Evenements\ChampPerso::new

champPerso_create:
    path:     /create
    controller: App\Controller\Evenements\ChampPerso::create
    requirements: { methods: post }

champPerso_edit:
    path:     /evenement-{idevenement}/{generation}
    controller: App\Controller\Evenements\ChampPerso::edit
    default:
        generation : edit
    requirements: 
        generation: generate|edit

champPerso_update:
    path:     /{id}/update
    controller: App\Controller\Evenements\ChampPerso::update
    requirements: { methods: post|put }

champPerso_delete:
    path:     /{id}/delete
    controller: App\Controller\Evenements\ChampPerso::delete
    requirements: { methods: post|delete }

champPerso_reponse:
    path:     /update/reponse
    controller: App\Controller\Evenements\ChampPerso::reponse
    requirements: { methods: post }