convention:
    path:     /{slug}
    controller: App\Controller\Evenements\Convention::index
    default:
        slug: 1

convention_show:
    path:     /{id}/show
    controller: App\Controller\Evenements\Convention::show

convention_new:
    path:     /inscription-{idinscription}/new
    controller: App\Controller\Evenements\Convention::new

convention_create:
    path:     /inscription-{idinscription}/create
    controller: App\Controller\Evenements\Convention::create
    requirements: { methods: post }

convention_edit:
    path:     /{id}/edit
    controller: App\Controller\Evenements\Convention::edit

convention_update:
    path:     /{id}/update
    controller: App\Controller\Evenements\Convention::update
    requirements: { methods: post|put }

convention_delete:
    path:     /{id}/delete
    controller: App\Controller\Evenements\Convention::delete
    requirements: { methods: post|delete }

convention_derniernumero:
    path:     /ajax/derniernumero
    controller: App\Controller\Evenements\Convention::derniernumero
    requirements: { methods: post }

convention_createConvention:
    path:     /ajax/createConvention
    controller: App\Controller\Evenements\Convention::createConvention
    requirements: { methods: post }

convention_updateetape:
    path:     /ajax/updateConvention
    controller: App\Controller\Evenements\Convention::updateConvention
    requirements: { methods: post }
