evenement:
    path:     /{type}/
    controller: App\Controller\Evenements\Evenement::index
    defaults:
        type: 'formation'
    requirements: { type: formation|event }

evenement_show:
    path:     /{id}/show
    controller: App\Controller\Evenements\Evenement::show

evenement_new:
    path:     /{type}/new
    controller: App\Controller\Evenements\Evenement::new
    defaults:
        type: 'formation'
    requirements: { type: formation|event }

evenement_create:
    path:     /create
    controller: App\Controller\Evenements\Evenement::create
    requirements: { methods: post }

evenement_edit:
    path:     /{id}/edit
    controller: App\Controller\Evenements\Evenement::edit

evenement_update:
    path:     /{id}/update
    controller: App\Controller\Evenements\Evenement::update
    requirements: { methods: post|put }

evenement_delete:
    path:     /{id}/delete
    controller: App\Controller\Evenements\Evenement::delete
    requirements: { methods: post|delete }

evenement_addtype:
    path:     /nouveau-type
    controller: App\Controller\Evenements\Evenement::ajoutType
    requirements: { methods: post }

evenement_addintervenants:
    path:     /{idevenement}/intervenant
    controller: App\Controller\Evenements\Evenement::indexIntervenantEvenement

evenement_intervenants_update:
    path:     /{idevenement}/intervenant_update
    controller: App\Controller\Evenements\Evenement::updateIntervenantEvenement
    requirements: { methods: put }
