formule:
    path:     /
    controller: App\Controller\Evenements\Formule::index

formule_show:
    path:     /{id}/show
    controller: App\Controller\Evenements\Formule::show

formule_new:
    path:     /new
    controller: App\Controller\Evenements\Formule::new

formule_create:
    path:     /create
    controller: App\Controller\Evenements\Formule::create
    requirements: { methods: post }

formule_edit:
    path:     /{id}/edit
    controller: App\Controller\Evenements\Formule::edit

formule_update:
    path:     /{id}/update
    controller: App\Controller\Evenements\Formule::update
    requirements: { methods: post|put }

formule_delete:
    path:     /{id}/delete
    controller: App\Controller\Evenements\Formule::delete
    requirements: { methods: post|delete }
