knp_snappy:
    pdf:
        enabled:    true
        binary:     wkhtmltopdf
        options:
          - { name: page-size, value: A4 }
          - { name: zoom, value: 1 }
          - { name: encoding, value: utf-8 }
          - { name: dpi , value: 300 }
          - { name: image-dpi , value: 300 }
          - { name: image-quality , value: 100 }
          - { name: margin-bottom , value: 7 }
          - { name: margin-top , value: 7 }
          - { name: margin-right , value: 7 }
          - { name: margin-left , value: 7 }
          - { name: page-width  , value: 210 }
          - { name: page-height  , value: 297 }
          - { name: disable-smart-shrinking  , value: false }
          - { name: lowquality  , value: false }

    image:
        enabled:    false
        binary:     wkhtmltoimage
        options:    []