parameters:
#    ocim_forma_gest.example.class: OCIM\FormaGestBundle\Example

services:
#    ocim_forma_gest.example:
#        class: %ocim_forma_gest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
