ocim_evenements_convention:
    resource: "@OCIMEvenementsBundle/Resources/config/routing/convention.yaml"
    prefix:   /convention

OCIMEvenementsBundle_champPerso:
    resource: "@OCIMEvenementsBundle/Resources/config/routing/champPerso.yaml"
    prefix:   /champPerso