OCIM\UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: OCIM\UserBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dn:
            type: string
            length: 255
        name:
            type: string
            length: 255
        language:
            type: string
            length: 255
    lifecycleCallbacks: {  }
