inscriptionpublique_creation:
    path:     /
    controller: App\Controller\Evenements\InscriptionPublique::createInscription
    requirements: { methods: post }

inscriptionpublique:
    path:     /
    controller: App\Controller\Evenements\InscriptionPublique::inscription
    requirements: { methods: get }
