inscriptionpublique_creation:
    path:     /
    controller: App\Controller\Evenements\InscriptionPubliqueController::createInscription
    requirements: { methods: post }

inscriptionpublique:
    path:     /
    controller: App\Controller\Evenements\InscriptionPubliqueController::inscription
    requirements: { methods: get }
