<?php

namespace OCIM\EvenementsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
	public function findAll()
    {
			return $this->getEntityManager()
				->createQuery(
					'SELECT f FROM OCIMEvenementsBundle:Evenement f'
				)
				->getResult();
    }

	public function findAllFutursEvenements(){
		return $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM OCIMEvenementsBundle:Evenement f
								WHERE f.dateFin >= :date
								ORDER BY f.dateDebut ASC'
            )->setParameter('date', new \DateTime('now'))
            ->getResult();
	}
}
