user:
    path:     /
    controller: App\Controller\User\UserController::index

user_show:
    path:     /{id}/show
    controller: App\Controller\User\UserController::show

user_new:
    path:     /new
    controller: App\Controller\User\UserController::new

user_create:
    path:     /create
    controller: App\Controller\User\UserController::create
    requirements: { methods: post }

user_edit:
    path:     /{id}/edit
    controller: App\Controller\User\UserController::edit

user_update:
    path:     /{id}/update
    controller: App\Controller\User\UserController::update
    requirements: { methods: post|put }

user_delete:
    path:     /{id}/delete
    controller: App\Controller\User\UserController::delete
    requirements: { methods: post|delete }
