user:
    path:     /
    controller: App\Controller\User\User::index

user_show:
    path:     /{id}/show
    controller: App\Controller\User\User::show

user_new:
    path:     /new
    controller: App\Controller\User\User::new

user_create:
    path:     /create
    controller: App\Controller\User\User::create
    requirements: { methods: post }

user_edit:
    path:     /{id}/edit
    controller: App\Controller\User\User::edit

user_update:
    path:     /{id}/update
    controller: App\Controller\User\User::update
    requirements: { methods: post|put }

user_delete:
    path:     /{id}/delete
    controller: App\Controller\User\User::delete
    requirements: { methods: post|delete }
