ocim_contacts:
    resource: "@OCIMContactsBundle/Resources/config/routing.yml"
    prefix:   /

ocim_export:
    resource: "@OCIMExportBundle/Resources/config/routing.yml"
    prefix:   /

ocim_user:
    resource: "@OCIMUserBundle/Resources/config/routing.yml"
    prefix:   /

ocim_formations:
    resource: "@OCIMFormationsBundle/Resources/config/routing.yml"
    prefix:   /

OCIMFormationsBundle_formation:
    resource: "@OCIMFormationsBundle/Resources/config/routing/formation.yml"
    prefix:   /formation

OCIMFormationsBundle_formule:
    resource: "@OCIMFormationsBundle/Resources/config/routing/formule.yml"
    prefix:   /formule

OCIMFormationsBundle_inscription:
    resource: "@OCIMFormationsBundle/Resources/config/routing/inscription.yml"
    prefix:   /formation-{idformation}/inscriptions

OCIMContactsBundle_personne:
    resource: "@OCIMContactsBundle/Resources/config/routing/personne.yml"
    prefix:   /personne

OCIMUserBundle_user:
    resource: "@OCIMUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

connexion:
    pattern: /connexion
    defaults: { _controller: OCIMUserBundle:Admin:connexion }

check:
    pattern: /check

deconnexion:
    pattern: /deconnexion

home:
    pattern: /
    defaults: { _controller: OCIMFormationsBundle:Default:index }
