inscriptionpublique_creation:
    path:     /
    defaults: { _controller: OCIMFormationsBundle:InscriptionPublique:createInscription }
    requirements: { _method: post }

inscriptionpublique:
    path:     /formation/{rthsht}/
    defaults: { _controller: OCIMFormationsBundle:InscriptionPublique:inscription }
    requirements: { _method: get }
