ocim_contacts:
    resource: "@OCIMContactsBundle/Resources/config/routing.yml"
    prefix:   /

ocim_export:
    resource: "@OCIMExportBundle/Resources/config/routing.yml"
    prefix:   /

ocim_user:
    resource: "@OCIMUserBundle/Resources/config/routing.yml"
    prefix:   /

ocim_formations:
    resource: "@OCIMFormationsBundle/Resources/config/routing.yml"
    prefix:   /

OCIMFormationsBundle_formation:
    resource: "@OCIMFormationsBundle/Resources/config/routing/formation.yml"
    prefix:   /formation

OCIMFormationsBundle_formule:
    resource: "@OCIMFormationsBundle/Resources/config/routing/formule.yml"
    prefix:   /formule

connexion:
    pattern: /connexion
    defaults: { _controller: OCIMUserBundle:Admin:connexion }

check:
    pattern: /check

deconnexion:
    pattern: /deconnexion

home:
    pattern: /
    defaults: { _controller: OCIMFormationsBundle:Default:index }
