inscriptionpublique:
    path:     /
    defaults: { _controller: OCIMFormationsBundle:InscriptionPublique:inscription }

inscriptionpublique_creation:
    path:     /inscription-creation/{idformation}
    defaults: { _controller: OCIMFormationsBundle:InscriptionPublique:createInscription }
    requirements: { _method: post }
