security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        OCIM\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: {class: OCIM\UserBundle\Entity\User, property: mail}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/
            form_login:
                check_path: /check
                login_path: /connexion
                use_forward: true
            logout:
                path:   /deconnexion
                target: /
    access_control:
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
