<?php

namespace Proxies\__CG__\OCIM\EvenementsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class evenementFormule extends \OCIM\EvenementsBundle\Entity\evenementFormule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\evenementFormule' . "\0" . 'id', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\evenementFormule' . "\0" . 'modeles', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\evenementFormule' . "\0" . 'formule', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\evenementFormule' . "\0" . 'evenement', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\evenementFormule' . "\0" . 'inscriptions'];
        }

        return ['__isInitialized__', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\evenementFormule' . "\0" . 'id', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\evenementFormule' . "\0" . 'modeles', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\evenementFormule' . "\0" . 'formule', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\evenementFormule' . "\0" . 'evenement', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\evenementFormule' . "\0" . 'inscriptions'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (evenementFormule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addModele(\OCIM\EvenementsBundle\Entity\ModeleChampPerso $modeles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addModele', [$modeles]);

        return parent::addModele($modeles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeModele(\OCIM\EvenementsBundle\Entity\ModeleChampPerso $modeles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeModele', [$modeles]);

        return parent::removeModele($modeles);
    }

    /**
     * {@inheritDoc}
     */
    public function getModeles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModeles', []);

        return parent::getModeles();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormule(\OCIM\EvenementsBundle\Entity\Formule $formule = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormule', [$formule]);

        return parent::setFormule($formule);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormule', []);

        return parent::getFormule();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvenement(\OCIM\EvenementsBundle\Entity\Evenement $evenement = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvenement', [$evenement]);

        return parent::setEvenement($evenement);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvenement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvenement', []);

        return parent::getEvenement();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addInscription(\OCIM\EvenementsBundle\Entity\Inscription $inscriptions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInscription', [$inscriptions]);

        return parent::addInscription($inscriptions);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInscription(\OCIM\EvenementsBundle\Entity\Inscription $inscriptions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInscription', [$inscriptions]);

        return parent::removeInscription($inscriptions);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscriptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscriptions', []);

        return parent::getInscriptions();
    }

    /**
     * {@inheritDoc}
     */
    public function getFormuleId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormuleId', []);

        return parent::getFormuleId();
    }

}
