<?php

namespace Proxies\__CG__\OCIM\EvenementsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formule extends \OCIM\EvenementsBundle\Entity\Formule implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'id', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'description', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'tarif', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'midi', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'soir', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'nuit', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'evenementFormule'];
        }

        return ['__isInitialized__', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'id', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'description', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'tarif', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'midi', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'soir', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'nuit', '' . "\0" . 'OCIM\\EvenementsBundle\\Entity\\Formule' . "\0" . 'evenementFormule'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Formule $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarif($tarif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarif', [$tarif]);

        return parent::setTarif($tarif);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarif', []);

        return parent::getTarif();
    }

    /**
     * {@inheritDoc}
     */
    public function setMidi($midi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMidi', [$midi]);

        return parent::setMidi($midi);
    }

    /**
     * {@inheritDoc}
     */
    public function getMidi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMidi', []);

        return parent::getMidi();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoir($soir)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoir', [$soir]);

        return parent::setSoir($soir);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoir', []);

        return parent::getSoir();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuit($nuit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuit', [$nuit]);

        return parent::setNuit($nuit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuit', []);

        return parent::getNuit();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvenementFormule(\OCIM\EvenementsBundle\Entity\evenementFormule $evenementFormule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvenementFormule', [$evenementFormule]);

        return parent::addEvenementFormule($evenementFormule);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvenementFormule(\OCIM\EvenementsBundle\Entity\evenementFormule $evenementFormule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvenementFormule', [$evenementFormule]);

        return parent::removeEvenementFormule($evenementFormule);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvenementFormule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvenementFormule', []);

        return parent::getEvenementFormule();
    }

}
