ocim_contacts_intervenants:
    resource: "@OCIMContactsBundle/Resources/config/routing/intervenant.yml"
    prefix:   /intervenants

ocim_contacts_signataire:
    resource: "@OCIMContactsBundle/Resources/config/routing/signataire.yml"
    prefix:   /signataire

ocim_contacts_homepage:
    path:     /hello/{name}
    controller: App\Controller\Contacts\Default::index

structure_ajout:
    path:     structure_ajout
    controller: App\Controller\Contacts\Adresse::ajoutTypeStructure

structure:
    path:     structures
    controller: App\Controller\Contacts\Adresse::index
