documents:
    path:     /
    defaults: { _controller: "OCIMExportBundle:Template:index" }

documents_show:
    path:     /{id}/inscription-{idinscription}/show
    defaults: { _controller: "OCIMExportBundle:Template:show" }

documents_new:
    path:     /new
    defaults: { _controller: "OCIMExportBundle:Template:new" }

documents_create:
    path:     /create
    defaults: { _controller: "OCIMExportBundle:Template:create" }
    requirements: { _method: post }

documents_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCIMExportBundle:Template:edit" }

documents_update:
    path:     /{id}/update
    defaults: { _controller: "OCIMExportBundle:Template:update" }
    requirements: { _method: post|put }

documents_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCIMExportBundle:Template:delete" }
    requirements: { _method: post|delete }
