ocim_formations_convention:
    resource: "@OCIMFormationsBundle/Resources/config/routing/convention.yml"
    prefix:   /convention

OCIMFormationsBundle_logistique:
    resource: "@OCIMFormationsBundle/Resources/config/routing/logistique.yml"
    prefix:   /logistique