OCIM\ContactsBundle\Entity\Adresse:
    type: entity
    oneToOne:
        structure:
            targetEntity: Structure
            mappedBy: adresse
    table: null
    repositoryClass: OCIM\ContactsBundle\Entity\AdresseRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomStructure:
            type: string
            length: 255
            nullable: true
        adresse:
            type: string
            length: 255
            nullable: true
        adresseComplement:
            type: string
            length: 255
            nullable: true
        cP:
            type: string
            length: 255
            column: CP
            nullable: true
        ville:
            type: string
            length: 255
            nullable: true
        pays:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
