OCIM\ContactsBundle\Entity\Personne:
    type: entity
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discr
        type: string
    discriminatorMap:
        signataire: Signataire
        stagiaire: Stagiaire
        intervenant: Intervenant
    oneToOne:
        adresse:
            targetEntity: Adresse
            cascade: ["persist", 'remove']
            joinColumn:
                name: adresse_id
                referencedColumnName: id
    table: null
    repositoryClass: OCIM\ContactsBundle\Entity\PersonneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        civilite:
            type: string
            length: 255
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        fonction:
            type: string
            length: 255
        tel:
            type: string
            length: 255
        fax:
            type: string
            length: 255
            nullable: true
        mail:
            type: string
            length: 255
        mailAdmin:
            type: string
            length: 255
            nullable: true
        commentaire:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
