OCIM\ContactsBundle\Entity\Personne:
    type: entity
    oneToOne:
        adresse:
            targetEntity: Adresse
            joinColumn:
                name: adresse_id
                referencedColumnName: id
        inscription:
            targetEntity: OCIM\FormationsBundle\Entity\Inscription
            mappedBy: personne
    manyToOne:
        type:
            targetEntity: TypePersonne
            inversedBy: personnes
            joinColumn:
                name: type_id
                referencedColumnName: id
    table: null
    repositoryClass: OCIM\ContactsBundle\Entity\PersonneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        civilite:
            type: string
            length: 255
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        fonction:
            type: string
            length: 255
        tel:
            type: string
            length: 255
        fax:
            type: string
            length: 255
        mail:
            type: string
            length: 255
        mailAdmin:
            type: string
            length: 255
    lifecycleCallbacks: {  }
