OCIM\ContactsBundle\Entity\Structure:
    type: entity
    oneToOne:
        adresse:
            targetEntity: Adresse
            inversedBy: structure
            cascade: ["all"]
            joinColumn:
                adresse_id:
                    referencedColumnName: id
    manyToOne:
        type:
            targetEntity: TypeStructure
            inversedBy: structure
            joinColumn:
                name: type_id
                referencedColumnName: id
    manyToMany:
        tags:
            targetEntity: TagStructure
            inversedBy: structures
            cascade: ["all"]
            joinTable:
                name: structures_tags
                joinColumns:
                    structure_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tagStructure_id:
                        referencedColumnName: id
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
    lifecycleCallbacks: {  }