intervenants:
    path:     /
    controller: App\Controller\Contacts\Intervenant::index

intervenants_show:
    path:     /evenement-{idevenement}/{id}/show
    controller: App\Controller\Contacts\Intervenant::show

intervenants_new:
    path:     evenement/{idevenement}/new
    controller: App\Controller\Contacts\Intervenant::new
    defaults:
        idevenement: 'null'

intervenants_create:
    path:     /evenement-{idevenement}/create/
    controller: App\Controller\Contacts\Intervenant::create
    requirements: { methods: post }

intervenants_edit:
    path:     /evenement/{idevenement}/{id}/edit
    controller: App\Controller\Contacts\Intervenant::edit
    defaults:
        idevenement: 'null'

intervenants_update:
    path:     /evenement-{idevenement}/{id}/update
    controller: App\Controller\Contacts\Intervenant::update
    requirements: { methods: post|put }

intervenants_delete:
    path:     /evenement-{idevenement}/{id}/delete
    controller: App\Controller\Contacts\Intervenant::delete
    requirements: { methods: post|delete }
