personne:
    path:     /
    controller: App\Controller\Contacts\PersonneController::index

personne_show:
    path:     /{id}/show
    controller: App\Controller\Contacts\PersonneController::show

personne_new:
    path:     /new
    controller: App\Controller\Contacts\PersonneController::new

personne_create:
    path:     /create
    controller: App\Controller\Contacts\PersonneController::create
    requirements: { methods: post }

personne_edit:
    path:     /{id}/edit
    controller: App\Controller\Contacts\PersonneController::edit

personne_update:
    path:     /{id}/update
    controller: App\Controller\Contacts\PersonneController::update
    requirements: { methods: post|put }

personne_delete:
    path:     /{id}/delete
    controller: App\Controller\Contacts\PersonneController::delete
    requirements: { methods: post|delete }
