personne:
    path:     /
    controller: App\Controller\Contacts\Personne::index

personne_show:
    path:     /{id}/show
    controller: App\Controller\Contacts\Personne::show

personne_new:
    path:     /new
    controller: App\Controller\Contacts\Personne::new

personne_create:
    path:     /create
    controller: App\Controller\Contacts\Personne::create
    requirements: { methods: post }

personne_edit:
    path:     /{id}/edit
    controller: App\Controller\Contacts\Personne::edit

personne_update:
    path:     /{id}/update
    controller: App\Controller\Contacts\Personne::update
    requirements: { methods: post|put }

personne_delete:
    path:     /{id}/delete
    controller: App\Controller\Contacts\Personne::delete
    requirements: { methods: post|delete }
