OCIM\FormationsBundle\Entity\Convention:
    type: entity
    table: null
    oneToOne:
        inscription:
            targetEntity: Inscription
            mappedBy: convention
    repositoryClass: OCIM\FormationsBundle\Entity\ConventionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        numero:
            type: integer
        edition:
            type: date
            nullable: true
        etape1:
            type: date
            nullable: true
        etape2:
            type: date
            nullable: true
        etape3:
            type: date
            nullable: true
    lifecycleCallbacks: {  }
