OCIM\FormationsBundle\Entity\Convention:
    type: entity
    table: null
    oneToOne:
        inscription:
            targetEntity: Inscription
            mappedBy: convention
    repositoryClass: OCIM\FormationsBundle\Entity\ConventionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        numero:
            type: string
            length: 255
        edition:
            type: date
            nullable: true
        envoiPresidentU2ex:
            type: date
            nullable: true
        retourPresidentU2ex:
            type: date
            nullable: true
        envoiOrganisme2ex:
            type: date
            nullable: true
        retourOrganisme1ex:
            type: date
            nullable: true
        envoiPresidentU1ex:
            type: date
            nullable: true
    lifecycleCallbacks: {  }
