OCIM\FormationsBundle\Entity\Formation:
    type: entity
    manyToOne:
      type:
        targetEntity: TypeFormation
        inversedBy: formations
        joinColumn:
            name: type_id
            referencedColumnName: id
    oneToMany:
        formationFormule:
            targetEntity: formationFormule
            mappedBy: formation
            cascade: ["all"]
        modelesIntervenants:
            targetEntity: ModeleLogistique
            mappedBy: formation
    manyToMany:
        intervenants:
            inversedBy: formations
            targetEntity: OCIM\ContactsBundle\Entity\Intervenant
            joinTable:
                name: Intervenants
                joinColumns:
                    formation_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    intervenant_id:
                        referencedColumnName: id
                        unique: true
    table: null
    repositoryClass: OCIM\FormationsBundle\Entity\FormationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        intitule:
            type: string
            length: 255
        lieu:
            type: string
            length: 255
        dateDebut:
            type: date
        dateFin:
            type: date
        dateText:
            type: string
            length: 255
        nbHeures:
            type: decimal
            scale: 1
            precision: 5
    lifecycleCallbacks: {  }
