OCIM\FormationsBundle\Entity\Formation:
    type: entity
    manyToOne:
      type:
        targetEntity: TypeFormation
        inversedBy: formations
        joinColumn:
            name: type_id
            referencedColumnName: id
    oneToMany:
        formationFormule:
            targetEntity: formationFormule
            fetch: EAGER
            mappedBy: formation
            cascade: ["all"]
        intervenants:
            targetEntity: OCIM\ContactsBundle\Entity\Intervenant
            mappedBy: formation
    table: null
    repositoryClass: OCIM\FormationsBundle\Entity\FormationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        intitule:
            type: string
            length: 255
        lieu:
            type: string
            length: 255
        dateDebut:
            type: date
        dateFin:
            type: date
        dateText:
            type: string
            length: 255
        nbHeures:
            type: decimal
            scale: 1
            precision: 5
    lifecycleCallbacks: {  }
