OCIM\FormationsBundle\Entity\Formule:
    type: entity
    manyToMany:
      formations:
        targetEntity: Formation
        inversedBy: formules
        joinTable:
          name: formation_formule
          joinColumns:
            formule_id:
              referencedColumnName: id
          inverseJoinColumns:
            formation_id:
              referencedColumnName: id
    table: null
    repositoryClass: OCIM\FormationsBundle\Entity\FormuleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
        tarif:
            type: string
            length: 255
        midi:
            type: boolean
        soir:
            type: boolean
        nuit:
            type: boolean
    lifecycleCallbacks: {  }
