OCIM\FormationsBundle\Entity\formationFormule:
    type: entity
    manyToOne:
        formule:
            targetEntity: Formule
            inversedBy: formationFormule
            fetch: EAGER
            cascade: ["persist"]
            joinColumn:
                name: formule_id
                referencedColumnName: id
                onDelete: CASCADE
        formation:
            targetEntity: Formation
            inversedBy: formationFormule
            fetch: EAGER
            cascade: ["persist"]
            joinColumn:
                name: formation_id
                referencedColumnName: id
                onDelete: CASCADE
    oneToMany:
        inscriptions:
            targetEntity: Inscription
            mappedBy: formationformule
            cascade: ["persist"]
    manyToMany:
        modeles:
            targetEntity: ModeleLogistique
            inversedBy: formationformule
            cascade: ["persist"]
            joinTable:
                name: formationformule_modele
                joinColumns:
                    formationformule_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    modele_id:
                        referencedColumnName: id
    table: formation_formule
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }