OCIM\FormationsBundle\Entity\Formule:
    type: entity
    table: null
    oneToMany:
        formations:
            targetEntity: formationFormule
            mappedBy: formules
            cascade: [persist]
    repositoryClass: OCIM\FormationsBundle\Entity\FormuleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
        tarif:
            type: string
            length: 255
        midi:
            type: boolean
        soir:
            type: boolean
        nuit:
            type: boolean
    lifecycleCallbacks: {  }
