OCIM\FormationsBundle\Entity\formationFormule:
    type: entity
    manyToOne:
        formule:
            targetEntity: Formule
            inversedBy: formationFormule
            fetch: EAGER
            cascade: ["all"]
            joinColumn:
                name: formule_id
                referencedColumnName: id
        formation:
            targetEntity: Formation
            inversedBy: formationFormule
            fetch: EAGER
            cascade: ["all"]
            joinColumn:
                name: formation_id
                referencedColumnName: id
    oneToMany:
        modeles:
            targetEntity: ModeleLogistique
            mappedBy: formationformule
            cascade: ["all"]
        inscriptions:
            targetEntity: Inscription
            mappedBy: formationformule
            cascade: ["all"]
    table: formation_formule
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }