OCIM\FormationsBundle\Entity\Inscription:
    type: entity
    table: null
    oneToOne:
        convention:
            targetEntity: Convention
            inversedBy: inscription
            joinColumn:
                convention_id:
                    referencedColumnName: id
    manyToOne:
        formationformule:
            targetEntity: formationFormule
            inversedBy: inscriptions
            joinColumn:
                onDelete: CASCADE
                formationformule_id:
                    referencedColumnName: id
    oneToMany:
        reponsesInscription:
            targetEntity: ReponsesLogistique
            mappedBy: inscrit
    manyToMany:
        personnes:
            targetEntity: OCIM\ContactsBundle\Entity\Personne
            cascade: ["persist", "remove"]
            fetch: EAGER
            joinTable:
                name: inscription_personnes
                cascade: ["persist", "remove"]
                joinColumns:
                    inscription_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    personne_id:
                        referencedColumnName: id
                        unique: true
                        onDelete: CASCADE
    repositoryClass: OCIM\FormationsBundle\Entity\InscriptionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateInscription:
            type: datetime
        statut:
            type: string
            length: 255
        attentes:
            type: text
        statutOrgFinanceur:
            type: string
            length: 255
            nullable: true
        statutConvention:
            type: string
            length: 255
            nullable: true
        hash:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: 
        prePersist: [ onPrePersist ]