OCIM\FormationsBundle\Entity\Inscription:
    type: entity
    table: null
    oneToOne:
        convention:
            targetEntity: Convention
            inversedBy: inscription
            joinColumn:
                convention_id:
                    referencedColumnName: id
    manyToOne:
        formationformule:
            targetEntity: formationFormule
            inversedBy: inscriptions
            joinColumn:
                formationformule_id:
                    referencedColumnName: id
    oneToMany:
        reponsesInscription:
            targetEntity: ReponsesLogistique
            mappedBy: inscrit
    repositoryClass: OCIM\FormationsBundle\Entity\InscriptionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateInscription:
            type: datetime
        statut:
            type: string
            length: 255
        attentes:
            type: text
        statutOrgFinanceur:
            type: string
            length: 255
        statutConvention:
            type: string
            length: 255
        hash:
            type: string
            length: 255
    lifecycleCallbacks: {  }
