OCIM\FormationsBundle\Entity\ModeleLogistique:
    type: entity
    oneToMany:
        reponses:
            targetEntity: ReponsesLogistique
            mappedBy: modele
    manyToOne:
        formationformule:
            targetEntity: formationFormule
            inversedBy: modeles
            joinColumn:
                name: formationformule_id
                referencedColumnName: id
    table: null
    repositoryClass: OCIM\FormationsBundle\Entity\ModeleLogistiqueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        description:
            type: string
            length: 255
        typeReponse:
            type: string
            length: 255
    lifecycleCallbacks: {  }
