OCIM\FormationsBundle\Entity\ModeleChampPerso:
    type: entity
    oneToMany:
        reponses:
            targetEntity: ReponsesChampPerso
            mappedBy: modele
            cascade: ['all']
    manyToMany:
        formationFormule:
            cascade: ['persist']
            targetEntity: formationFormule
            mappedBy: modeles
    manyToOne:
        formation:
            targetEntity: Formation
            inversedBy: modelesIntervenants
            joinColumn:
                name: formation_id
                referencedColumnName: id
    table: null
    repositoryClass: OCIM\FormationsBundle\Entity\ModeleChampPersoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
            nullable: true
        description:
            type: string
            length: 255
        typeReponse:
            type: string
            length: 255
        ordre:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
