OCIM\FormationsBundle\Entity\ReponsesLogistique:
    type: entity
    manyToOne:
        modele:
            targetEntity: ModeleLogistique
            inversedBy: reponses
            joinColumn:
                name: modele_id
                referencedColumnName: id
        inscription:
            targetEntity: Inscription
            inversedBy: reponsesLogistique
            joinColumn:
                name: inscription_id
                referencedColumnName: id
    table: null
    repositoryClass: OCIM\FormationsBundle\Entity\ReponsesLogistiqueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        reponse:
            type: boolean
            nullable: true
        reponseText:
            type: string
            length: 255
            nullable: true
        date:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
