OCIM\FormationsBundle\Entity\TypeFormation:
    type: entity
    oneToMany:
      formations:
        targetEntity: Formation
        mappedBy: type
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
    lifecycleCallbacks: {  }
