<?php

namespace App\Entity\Evenements;

use Doctrine\ORM\EntityRepository;

/**
 * evenementFormuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class evenementFormuleRepository extends EntityRepository
{

}
