<?php

namespace App\Entity\Evenements;

use Doctrine\ORM\EntityRepository;

/**
 * FormuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormuleRepository extends EntityRepository
{
}
