convention:
    path:     /{slug}
    defaults: { _controller: "OCIMFormationsBundle:Convention:index", slug:1}

convention_show:
    path:     /{id}/show
    defaults: { _controller: "OCIMFormationsBundle:Convention:show" }

convention_new:
    path:     /inscription-{idinscription}/new
    defaults: { _controller: "OCIMFormationsBundle:Convention:new" }

convention_create:
    path:     /inscription-{idinscription}/create
    defaults: { _controller: "OCIMFormationsBundle:Convention:create" }
    requirements: { _method: post }

convention_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCIMFormationsBundle:Convention:edit" }

convention_update:
    path:     /{id}/update
    defaults: { _controller: "OCIMFormationsBundle:Convention:update" }
    requirements: { _method: post|put }

convention_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCIMFormationsBundle:Convention:delete" }
    requirements: { _method: post|delete }

convention_derniernumero:
    path:     /ajax/derniernumero
    defaults: { _controller: "OCIMFormationsBundle:Convention:derniernumero" }
    requirements: { _method: post }




convention_createConvention:
    path:     /ajax/createConvention
    defaults: { _controller: "OCIMFormationsBundle:Convention:createConvention" }
    requirements: { _method: post }
