evenement:
    path:     /
    defaults: { _controller: "OCIMFormationsBundle:Evenement:index" }

evenement_show:
    path:     /{id}/show
    defaults: { _controller: "OCIMFormationsBundle:Evenement:show" }

evenement_new:
    path:     /new
    defaults: { _controller: "OCIMFormationsBundle:Evenement:new" }

evenement_create:
    path:     /create
    defaults: { _controller: "OCIMFormationsBundle:Evenement:create" }
    requirements: { _method: post }

evenement_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCIMFormationsBundle:Evenement:edit" }

evenement_update:
    path:     /{id}/update
    defaults: { _controller: "OCIMFormationsBundle:Evenement:update" }
    requirements: { _method: post|put }

evenement_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCIMFormationsBundle:Evenement:delete" }
    requirements: { _method: post|delete }

evenement_addtype:
    path:     /nouveau-type
    defaults: { _controller: "OCIMFormationsBundle:Evenement:ajoutType" }
    requirements: { _method: post }

evenement_addintervenants:
    path:     /{idevenement}/intervenant
    defaults: { _controller: "OCIMFormationsBundle:Evenement:indexIntervenantFormation" }

evenement_intervenants_update:
    path:     /{idevenement}/intervenant_update
    defaults: { _controller: "OCIMFormationsBundle:Evenement:updateIntervenantFormation" }
    requirements: { _method: put }
