formation:
    path:     /
    defaults: { _controller: "OCIMFormationsBundle:Formation:index" }

formation_show:
    path:     /{id}/show
    defaults: { _controller: "OCIMFormationsBundle:Formation:show" }

formation_new:
    path:     /new
    defaults: { _controller: "OCIMFormationsBundle:Formation:new" }

formation_create:
    path:     /create
    defaults: { _controller: "OCIMFormationsBundle:Formation:create" }
    requirements: { _method: post }

formation_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCIMFormationsBundle:Formation:edit" }

formation_update:
    path:     /{id}/update
    defaults: { _controller: "OCIMFormationsBundle:Formation:update" }
    requirements: { _method: post|put }

formation_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCIMFormationsBundle:Formation:delete" }
    requirements: { _method: post|delete }

formation_addtype:
    path:     /nouveau-type
    defaults: { _controller: "OCIMFormationsBundle:Formation:ajoutType" }
    requirements: { _method: post }

formation_addintervenants:
    path:     /{idformation}/intervenant
    defaults: { _controller: "OCIMFormationsBundle:Formation:indexIntervenantFormation" }

formation_intervenants_update:
    path:     /{idformation}/intervenant_update
    defaults: { _controller: "OCIMFormationsBundle:Formation:updateIntervenantFormation" }
    requirements: { _method: put }
