inscription:
    path:     /formation-{id}
    defaults: { _controller: "OCIMFormationsBundle:Inscription:index" }

inscription_show:
    path:     /formation-{idformation}/{id}/show
    defaults: { _controller: "OCIMFormationsBundle:Inscription:show" }

inscription_new:
    path:     /new/formation-{idformation}
    defaults: { _controller: "OCIMFormationsBundle:Inscription:new" }

inscription_create:
    path:     /create/formation-{idformation}
    defaults: { _controller: "OCIMFormationsBundle:Inscription:create" }
    requirements: { _method: post }

inscription_edit:
    path:     /formation-{idformation}/edit-{id}
    defaults: { _controller: "OCIMFormationsBundle:Inscription:edit" }

inscription_update:
    path:     /formation-{idformation}/{id}/update
    defaults: { _controller: "OCIMFormationsBundle:Inscription:update" }
    requirements: { _method: post|put }

inscription_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCIMFormationsBundle:Inscription:delete" }
    requirements: { _method: post|delete }
