inscription:
    path:     /
    defaults: { _controller: "OCIMFormationsBundle:Inscription:index" }

inscription_show:
    path:     /{id}/show
    defaults: { _controller: "OCIMFormationsBundle:Inscription:show" }

inscription_new:
    path:     /new
    defaults: { _controller: "OCIMFormationsBundle:Inscription:new" }

inscription_create:
    path:     /create
    defaults: { _controller: "OCIMFormationsBundle:Inscription:create" }
    requirements: { _method: post }

inscription_edit:
    path:     /{id}/edit
    defaults: { _controller: "OCIMFormationsBundle:Inscription:edit" }

inscription_update:
    path:     /{id}/update
    defaults: { _controller: "OCIMFormationsBundle:Inscription:update" }
    requirements: { _method: post|put }

inscription_delete:
    path:     /{id}/delete
    defaults: { _controller: "OCIMFormationsBundle:Inscription:delete" }
    requirements: { _method: post|delete }
