ocim_contacts_structures:
    resource: "@OCIMContactsBundle/Resources/config/routing/structure.yml"
    prefix:   /structures

ocim_contacts_intervenants:
    resource: "@OCIMContactsBundle/Resources/config/routing/intervenant.yml"
    prefix:   /intervenants

ocim_contacts_signataire:
    resource: "@OCIMContactsBundle/Resources/config/routing/signataire.yml"
    prefix:   /signataire

ocim_contacts_homepage:
    path:     /hello/{name}
    defaults: { _controller: OCIMContactsBundle:Default:index }
