<?php

namespace OCIM\FormationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
	public function findAll()
    {
			return $this->getEntityManager()
				->createQuery(
					'SELECT f FROM OCIMFormationsBundle:Event f'
				)
				->getResult();
    }

	public function findAllFutursEvents(){
		return $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM OCIMFormationsBundle:Event f
								WHERE f.dateFin >= :date
								ORDER BY f.dateDebut ASC'
            )->setParameter('date', new \DateTime('now'))
            ->getResult();
	}
}
