<?php

namespace OCIM\FormationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{
	public function findAll()
    {
        return $this->findBy(array(), array('dateDebut' => 'ASC'));
    }
	
	public function findAllFutursFormations(){
		return $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM OCIMFormationsBundle:Formation f
				WHERE f.dateFin >= :date' 
            )->setParameter('date', new \DateTime('now'))
            ->getResult();
	}
}
