<?php

namespace OCIM\FormationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionRepository extends EntityRepository
{
	public function findAllByFormation($formation_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i, f FROM OCIMFormationsBundle:Inscription i
				JOIN i.formationformule f
				WHERE f.formation = :id'
            )->setParameter('id', $formation_id)
            ->getResult();
    }
}
