<?php

namespace OCIM\FormationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModeleChampPersoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleChampPersoRepository extends EntityRepository
{
	public function findModelesByIdFormation($idformation){
			return $this->getEntityManager()
				->createQuery(
					'SELECT mo FROM OCIMFormationsBundle:ModeleChampPerso mo
					LEFT JOIN mo.formationFormule ff
					WHERE ff.formation = :id
					OR mo.formation = :id
					ORDER BY mo.ordre ASC'
				)->setParameter('id', $idformation)
				->getResult();
		}
}
