<?php

namespace OCIM\FormationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModeleLogistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleLogistiqueRepository extends EntityRepository
{
	public function findModelesByIdFormation($idformation){
			return $this->getEntityManager()
				->createQuery(
					'SELECT mo FROM OCIMFormationsBundle:ModeleLogistique mo
					JOIN mo.formationFormule ff
					WHERE ff.formation = :id' 
				)->setParameter('id', $idformation)
				->getResult();
		}
}
