<?php

namespace OCIM\FormationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModeleLogistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeleLogistiqueRepository extends EntityRepository
{
}
