<?php

namespace App\Repository\Evenements;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository
{
	public function findAll()
    {
			return $this->getEntityManager()
				->createQuery(
					'SELECT f FROM App\Entity\Evenements\Evenement f'
				)
				->getResult();
    }

	public function findAllFutursEvents(){
		return $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM App\Entity\Evenements\Event f
								WHERE f.dateFin >= :date
								ORDER BY f.dateDebut ASC'
            )->setParameter('date', new \DateTime('now'))
						->setMaxResults(10)
            ->getResult();
	}

	public function findAllFutursFormations(){
		return $this->getEntityManager()
            ->createQuery(
                'SELECT f FROM App\Entity\Evenements\Formation f
								WHERE f.dateFin >= :date
								ORDER BY f.dateDebut ASC'
            )->setParameter('date', new \DateTime('now'))
						->setMaxResults(10)
            ->getResult();
	}
}
