<?php

namespace App\Repository\Contacts;

use Doctrine\ORM\EntityRepository;

/**
 * TagStructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagStructureRepository extends EntityRepository
{
}
