Entity\Contacts\TagStructure:
    type: entity
    manyToMany:
        structures:
            targetEntity: Adresse
            mappedBy: tags
    table: null
    repositoryClass: Repository\Contacts\TagStructureRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tag:
            type: string
            length: 255
    lifecycleCallbacks: {  }
